# Generated by Django 2.1.2 on 2018-10-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbatimentoIPTU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '04 - Consultar Cashback IPTU',
                'verbose_name_plural': '04 - Consultar Cashback IPTU',
            },
        ),
        migrations.CreateModel(
            name='CadastrarArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '01 - Nova Região da Cidade',
                'verbose_name_plural': '01 - Nova Região da Cidade',
            },
        ),
        migrations.CreateModel(
            name='CadastrarMuda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '02 - Cadastrar Muda para Adoção',
                'verbose_name_plural': '02 - Cadastrar Muda para Adoção',
            },
        ),
        migrations.CreateModel(
            name='NovaQuest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '03 - Nova Quest para População',
                'verbose_name_plural': '03 - Nova Quest para População',
            },
        ),
    ]
