# Generated by Django 2.1.2 on 2018-10-21 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_city', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresacadastro',
            options={'verbose_name': '02 - Cadastro de Empresa', 'verbose_name_plural': '02 - Cadastro de Empresas'},
        ),
        migrations.AlterModelOptions(
            name='prefeituracadastro',
            options={'verbose_name': '01 - Cadastros de Prefeituras', 'verbose_name_plural': '01 - Cadastros de Prefeituras'},
        ),
        migrations.RemoveField(
            model_name='empresacadastro',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='empresacadastro',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='empresacadastro',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='prefeituracadastro',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='prefeituracadastro',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='prefeituracadastro',
            name='nome',
        ),
    ]
