# Generated by Django 2.1.2 on 2018-10-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuscarAreas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '01 - Árvores Patrocinadas',
                'verbose_name_plural': '01 - Árvores Patrocinadas',
            },
        ),
        migrations.CreateModel(
            name='CreditoC02',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '02 - Crédito de C02',
                'verbose_name_plural': '02 - Crédito de C02',
            },
        ),
    ]
